### ISSUE TITLE
Pass current file cwd and filename to XO

### ISSUE THREAD

**Issue by sindresorhus** [Semigradsky/xo-loader#12]
In the `xo.lintText()` method you need to pass in the file `cwd` and `filename` as options. Some rules depend on these being set.

See: https://github.com/sindresorhus/atom-linter-xo/blob/77dce8fd0074234132060fee3c0701c3564d7d90/lib/lint.js#L44-L45

**Comment by vith** [comment]
I was checking if I needed to file an issue about the `import/no-unresolved` errors I was getting but this sounds like it would be the root cause.

**Comment by ghost** [comment]
Indeed. Getting `import/no-unresolved' as well.
