### ISSUE TITLE
Using dependencies instead of peerDependencies for xo

### ISSUE THREAD

**Issue by ragingwind** [Semigradsky/xo-loader#5]
Would you update the version of xo or remove xo from peerDependencies to use the upper version of xo? xo has been released v0.16.0 but this loader still uses `^0.13.0` with semver that only for under v0.14.0 as you know. For many reason, other npm module are not anymore using peerDependencies.

**Comment by Semigradsky** [comment]
I have updated xo version

**Comment by ragingwind** [comment]
thanks a lot
